export enum pokemonsTypes {
    FETCH_POKEMONS_REQUEST = 'FETCH_POKEMONS_REQUEST',
    FETCH_POKEMON_BY_ID = 'FETCH_POKEMON_BY_ID',
    SET_POKEMONS = 'SET_POKEMONS',
    SET_POKEMON = 'SET_POKEMON',
    POKEMONS_REQUEST_FAILED = 'POKEMONS_REQUEST_FAILED',
}
